### ISSUE TITLE
How to tell how many profiles I can store?

### ISSUE THREAD

**Issue by AndySchroder** [estkme-group/lpac#100]
How to tell how many profiles I can store? I currently have two.  How many can a typical card store? I can't find any command that says what the capacity of the card is in terms of number of profiles remaning. I am finding the following output, but I'm not sure it is relevant.

```
                                     'extCardResource': {'freeNonVolatileMemory': 431881,
                                                         'freeVolatileMemory': 14742,
                                                         'installedApplication': 0},

```

**Comment by damonto** [comment]
It depends on your eSIM profile size

**Comment by AndySchroder** [comment]
what is a typical size profile?

**Comment by damonto** [comment]
There is no definite answer; most are between 10 and 150 KiB

**Comment by AndySchroder** [comment]
Is there a clear error message for when it is full vs some other problem? This unknown coupled with https://github.com/estkme-group/lpac/issues/101 can result in very expensive bugs considering many providers may not provide a refund or alternate activation code.

What are the units in the memory outputs I've pasted above? bytes, kilobytes (base 2) or kilobytes (base 10)?

**Comment by AndySchroder** [comment]
Is there a certain amount of volatile memory required to write an eSIM to non-volatile memory? If the numbers above from my card are in bytes (the smallest option), I should still be able to get two eSIM at your high estimate of 150kilobytes. Do you think https://github.com/estkme-group/lpac/issues/101 is not due to insufficient memory available then?

**Comment by damonto** [comment]
All eSIM profiles will be stored in NonVolatileMemory. The storage size unit is byte. 
`freeNonVolatileMemory / 1024 = KiB`
