### ISSUE TITLE
/lib64/libcurl.so.4: no version information available

### ISSUE THREAD

**Issue by bam80** [estkme-group/lpac#112]
Can't run downloaded [lpac release](https://github.com/estkme-group/lpac/releases/download/v2.0.1/lpac-linux-x86_64.zip):
```
$ ./lpac
lpac: /lib64/libcurl.so.4: no version information available (required by Downloads/lpac-linux-x86_64/lpac)
SCardListReaders() failed: 8010002E
APDU driver init failed
$
```

Fedora Linux 40

**Comment by bam80** [comment]
I don't have a card reader.
The error itself is unrelated to the card reader - if I compile myself, it's gone:
```
$ ./output/lpac 
SCardListReaders() failed: 8010002E
APDU driver init failed

**Comment by CoelacanthusHex** [comment]
`lpac: /lib64/libcurl.so.4: no version information available (required by Downloads/lpac-linux-x86_64/lpac)` is not an error but a warning. That's because your distro compiles curl without version symbol. It shouldn't cause any issue because the curl has stable ABI
