### ISSUE TITLE
DIY eSIM

### ISSUE THREAD

**Issue by danvoid** [estkme-group/lpac#128]
I’ve ordered few ST33G1M2 chips and soldered them on the DIY kit from taobao.
When I am trying to extract data using lpac I am getting the following error.

```json
{"type":"lpa","payload":{"code":-1,"message":"es9p_initiate_authentication","data":"tag : invalid child object: tag �: invalid length encoding: indicated length encoding with 1 bytes, but following byte are miss”}}
```

When trying to download eSIM profile I am getting Unsupported msg.

```json
{"type":"lpa","payload":{"code":-1,"message":"es9p_initiate_authentication","data":"Unsupported"}}
```

Can you help?

**Comment by septs** [comment]
Taobao ship ST33G and ST33J series chip, it's seems that it is not in MP (mass production)

Therefore none of them contain a usable CI (Certificate Issuer) certificate.

Suggest, Run `lpac chip info` command, if you see the chip `euiccCiPKIdListForSigning` field is empty, then this chip is unavailabled

**Comment by danvoid** [comment]
Yes, it is empty.
"euiccCiPKIdListForVerification": [
    "665a1433d67c1a2c5db8b52c967f10a057ba5cb2",
    "16b5d16048e3ea02bd4b606e5f77a4bf20808d83",
    "16704b7f351e3607f18c4b70005c3a003dfd414a"
  ],
  "euiccCiPKIdListForSigning": [],

**Comment by septs** [comment]
I think this chip has no value.

**Comment by rdtmaster** [comment]
Hi @danvoid, did you continue to try and find a working chip or bailed on this idea?

**Comment by danvoid** [comment]
I've tried 5 different chips from Taobao / Aliexpress, all of them are no use.

**Comment by rdtmaster** [comment]
@danvoid, 
> 've tried 5 different chips from Taobao / Aliexpress, all of them are no use.

Have you by chance tried Suyika Technology (shop104192953 on taobao)?

**Comment by danvoid** [comment]
No, they are not selling any.

**Comment by sasodoma** [comment]
Hi, sorry for reviving this thread, but I am in the same situation and this is the only place that I could find info about why the ST33G1M2 chips don't work. @septs you are knowledgable on the topic. The chips that I bought are sold as being for an iPhone XS. They also have empty `euiccCiPKIdListForSigning`, would you say that even if they were installed in an iPhone they would not work and thus the seller actually scammed me (or just didn't know any better) or would they work in an iPhone, but not when soldered to a SIM card?

**Comment by sasodoma** [comment]
If I buy an iPhone motherboard and then desolder the eSIM will it have the certificate?
