### ISSUE TITLE
eastcompeace eUICC card esim Profile cannot be enabled using pc/sc card reader

### ISSUE THREAD

**Issue by hiya699** [estkme-group/lpac#13]
I am currently connecting the usb smart card reader in both **windows 10** and **ubuntu 22** system environments. I can successfully download the esim Profile to the 5ber and esimme cards. I can successfully disable or delete the profile and set the nickname.
 but **lpac** cannot enable esim Profile,
When executing `/lpac profile enable xxxxxxxxxxx (iccid)`
Response `{"type":"lpa","payload":{"code":-1,"message":"es10c_enable_profile_iccid","data":"unknown"}}`
Viewing through the lpa-agent   also shows State: Disabled.
I haven't tested the LTE module yet.

**Comment by estkme** [comment]
Are you using 5ber.esim card?

**Comment by estkme** [comment]
sorry, i see you are using 5ber card.
5ber card changed its enable logic, it required a not standard version of enable sequence.
we have already located this issue, it will be fixed soon.

**Comment by estkme** [comment]
ps: some of 5ber & esimme card use same provider, maybe this issue is affected your esimme card too.

**Comment by hiya699** [comment]
Thank you for your reply.
i hope  it will be fixed soon.

**Comment by Leozaki** [comment]
#14

**Comment by hiya699** [comment]
> #14 

When executing the ‘enable’ command with the ‘RefreshFlag’ set to 0, it works.
