### ISSUE TITLE
Can "tranfer eSim Profile (ICCID)" be implemented?

### ISSUE THREAD

**Issue by lepras** [estkme-group/lpac#130]
Assuming the carrier doesn't lock ICCID to the IMEI or EID, 

Can a feature be implemented such that a command transfer ICCID from one EID to another ( i.e. in bw 2 sim readers)

**Comment by damonto** [comment]
It is impossible to transfer your eSIM profile to a new eUICC. If you want to install your eSIM profile on your new device you need to contact your carrier to get the information.

**Comment by damonto** [comment]
Some carriers allow you to install your eSIM profile on your new device after you have successfully deleting it from your old device.

**Comment by lepras** [comment]
> It is impossible to transfer your eSIM profile to a new eUICC.

Don't iPhone devices do it?

**Comment by damonto** [comment]
Apple has a cooperation with the carrier, so iPhone can use the carrier's private API to transfer your eSIM profile.

**Comment by septs** [comment]
SGP.22 v3.x starts of standardize Device Change and Profile Recovery, but no chips available

see <https://www.gsma.com/solutions-and-impact/technologies/esim/gsma_resources/sgp-22-v3-1/>
