### ISSUE TITLE
[Compiling Error] Could NOT find PCSCLite (missing: PCSCLITE_INCLUDE_DIR)

### ISSUE THREAD

**Issue by BenSuRently** [estkme-group/lpac#132]
Hi guys,
It occurs to me that when I run **cmake**:

> -- Checking for module 'libpcsclite'
> --   No package 'libpcsclite' found
> -- Could NOT find PCSCLite (missing: PCSCLITE_INCLUDE_DIR) 
> -- Configuring done (0.0s)
> CMake Error at driver/CMakeLists.txt:37 (target_link_libraries):
>   Target "euicc-drivers" links to:
> 
>     PCSCLite::PCSCLite
> 
>   but the target was not found.  Possible reasons include:
> 
>     * There is a typo in the target name.
>     * A find_package call is missing for an IMPORTED target.
>     * An ALIAS target is missing.

Any ideas about the compiling error?

BR
Ben

**Comment by damonto** [comment]
You must install libpcsclite-dev and libcurl first. The package name depends on your system.

**Comment by CoelacanthusHex** [comment]
Please execute `pkg-config --modversion libpcsclite` and paste the output here.

**Comment by BenSuRently** [comment]
> Please execute `pkg-config --modversion libpcsclite` and paste the output here.

Hi @damonto , here is the output:

pkg-config --modversion libpcsclite
Package libpcsclite was not found in the pkg-config search path.
Perhaps you should add the directory containing `libpcsclite.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libpcsclite' found

**Comment by CoelacanthusHex** [comment]
> > Please execute `pkg-config --modversion libpcsclite` and paste the output here.
> 
> Hi @CoelacanthusHex , here is the output:
> 
> pkg-config --modversion libpcsclite Package libpcsclite was not found in the pkg-config search path. Perhaps you should add the directory containing `libpcsclite.pc' to the PKG_CONFIG_PATH environment variable No package 'libpcsclite' found

Please execute `strace -e trace=%file pkg-config --modversion libpcsclite &> log.txt` and upload log.txt

**Comment by BenSuRently** [comment]
Cool @CoelacanthusHex , I can compile it after running ` export PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig/`. Thanks very much.
BR
Ben

**Comment by CoelacanthusHex** [comment]
> Cool @CoelacanthusHex , I can compile it after running ` export PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig/`. Thanks very much. BR Ben

It should be the default value, there must be some wrong thing in your system.

**Comment by BenSuRently** [comment]
> PKG_CONFIG_PATH

Okay, will check with the PKG_CONFIG_PATH
