### ISSUE TITLE
Issue compiling lpac for ARM 64 linux

### ISSUE THREAD

**Issue by l0git3k** [estkme-group/lpac#136]
Hello,

I use a Khadas VIM4 with the Ubuntu Server 5.15 Khadas official images. Recently, I bought the Quectel RM-500Q-GL and I need to be able to use esim on Linux.

The module works, I was able to install it using the repository provided by the Khadas team. However, in the documentation there is no integration of eSIM functions in the Quectel Connect Manager. I found an eSIM LPA Application Note document on the Quectel site, which seems to be another piece of software.

I made a request on the Quectel forum but was refused access to this software ([Esim Provisioning RM510Q-GL using LPAd software - #43 by silvia - 5G Module - Quectel Forums 2](https://forums.quectel.com/t/esim-provisioning-rm510q-gl-using-lpad-software/22278/43)).

Long story short, on the Khadas Forum they recommended me to try this lpac software. Unfortunately, there is no release for ARM 64 bits linux, so I tried to compile by myself but I've had several errors linked to erroneous file locations, I've solved them, but now I have this error and I'm stuck

```
[ 0%] Built target version
[ 4%] Linking C executable output/lpac
/usr/bin/ld: cannot find -leuicc-drivers: No such file or directory
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/lpac.dir/build.make:401: output/lpac] Error 1
make[1]: *** [CMakeFiles/Makefile2:84: CMakeFiles/lpac.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

Could you help me understand what's the leuicc-drivers and where I can find them ?

Thanks .

**Comment by septs** [comment]
Khadas VIM4 is SBC?

5.15 is Linux kernel version?

Ubuntu version is ?

**Comment by CoelacanthusHex** [comment]
> Long story short, on the Khadas Forum they recommended me to try this lpac software. Unfortunately, there is no release for ARM 64 bits linux, so I tried to compile by myself but I've had several errors linked to erroneous file locations, I've solved them, but now I have this error and I'm stuck
> 
> ```
> [ 0%] Built target version
> [ 4%] Linking C executable output/lpac
> /usr/bin/ld: cannot find -leuicc-drivers: No such file or directory
> collect2: error: ld returned 1 exit status
> make[2]: *** [CMakeFiles/lpac.dir/build.make:401: output/lpac] Error 1
> make[1]: *** [CMakeFiles/Makefile2:84: CMakeFiles/lpac.dir/all] Error 2
> make: *** [Makefile:136: all] Error 2
> ```

Could you provide the full build log?

> 
> Could you help me understand what's the leuicc-drivers and where I can find them ?

That's https://github.com/estkme-group/lpac/tree/main/driver. It should be built by cmake when you build lpac.

**Comment by damonto** [comment]
As there is no response for a long time, we will close this issue.
