### ISSUE TITLE
Error: missing definitions compiling qmi_helpers

### ISSUE THREAD

**Issue by ricardofcmartins** [estkme-group/lpac#142]
Hello,

I tried to compile lpac with LPAC_WITH_APDU_QMI_QRTR and LPAC_WITH_APDU_QMI
on Ubuntu and Debian latest, arm64 and amd64 variants.

It always resulted in the following missing definitions:
- unknown type name 'QmiMessageUimOpenLogicalChannelOutput'
- unknown type name 'QmiMessageUimOpenLogicalChannelInput'
- unknown type name 'QmiMessageUimLogicalChannelOutput'
- unknown type name 'QmiMessageUimLogicalChannelInput'
- unknown type name 'QmiMessageUimSendApduOutput'
- unknown type name 'QmiMessageUimSendApduInput'

Am I missing some dependency that is not caught by cmake?

**Comment by damonto** [comment]
The qmi drivers require libqmi 1.35.5 or later version, so you have to compile libqmi first.
