### ISSUE TITLE
 How do we get the corresponding ‘PEStatus’?

### ISSUE THREAD

**Issue by luyi58944** [estkme-group/lpac#156]
When ‘installFailedDueToPEProcessingError’ occurs, how do we get the corresponding ‘PEStatus’?
(https://github.com/user-attachments/assets/fc2fb5cd-3588-4f2c-b3ad-26bdc1574c35)

**Comment by septs** [comment]
PEStatus information not exported by the SGP.22 specification

Remap to ErrorReason ONLY

see https://www.gsma.com/solutions-and-impact/technologies/esim/wp-content/uploads/2020/06/SGP.22-v2.2.2.pdf#page=36
