### ISSUE TITLE
feature request: add a parameter to process deleted profiles Notifications

### ISSUE THREAD

**Issue by bam80** [estkme-group/lpac#158]
https://github.com/estkme-group/lpac/blob/0dcc94905e36d00fd682ce3eb02df1a33da8c03c/docs/USAGE.md?plain=1#L157-L158
We could add following parameters to the `profile delete` (and maybe others?) subcommand:
- `-p`: Process the deleted profiles notifications
- `-r`: Automatically remove processed notifications

**Comment by septs** [comment]
LPA does not know which notifications have been sent

**Comment by bam80** [comment]
Currently, a new notifications appears after profile delete, right?
That notifications are pending for processing in the suggestion.

**Comment by septs** [comment]
send notification after deleting profile?

**Comment by bam80** [comment]
> send notification after deleting profile?

Yes, because currently one have to do it manually by at least two sub-commands (`profile delete` and `notification process`), which is not very convenient.

**Comment by septs** [comment]
if after deleting profile needs send notification

then same applies to download profile, enable profile and disable profile

CC @estkme

**Comment by bam80** [comment]
> then same applies to download profile, enable profile and disable profile

might be. So we could have these parameters common for all of these sub-commands.
