### ISSUE TITLE
help needed: add support of some problematic eSIMs

### ISSUE THREAD

**Issue by bam80** [estkme-group/lpac#159]
As was [discussed earlier](https://github.com/estkme-group/lpac/issues/118#issuecomment-2169599234), some eSIMs are known to be not currently supported by Lpac.

It was claimed by Lpac developers (@CoelacanthusHex), the following lpac behavior problematic for some eSIMs is actually correct and does comply with the standard:

> **A APDU which needs response data can set N_e to any value including 0.** It followed the standard. If N_r is greater than N_e, the module should send data as much as possible with SW1=61 to tell the host there is still some data need to transfer. For this case, N_e is 0, so if there is response data, N_r is always greater than N_e and no response data can be sent. So the module need to sent SW1=61 and SW2 is data size and waiting for the host request again. There is no violation or error in the host side. All APDU sent by lpac is valid, just your module violate the standard and can't deal with an valid and regular APDU flow.

_Dear Lpac developers, could you help me to find the place in lpac code-base, responsible for this specific behavior of setting N_e (number of bytes expected in response ADPU data field) to 0?_

As I have such an eSIM, I could try to make a fix myself and give the results back.

The community would be gratitude to you,
Thank you.

**Comment by septs** [comment]
please provide some problem eSIM chips and ship to all developers

**Comment by bam80** [comment]
How do I do that?
