### ISSUE TITLE
No APDU driver found

### ISSUE THREAD

**Issue by max93776** [estkme-group/lpac#163]
Hi, I am trying to run lpac from the precompiled lpac-linux-x86_64.zip on my OpenMPTCProuter. My Modem communicates via at on port /dev/ttyUSB4, I have assigned all needed env variables, `ldd` shows, that all needed libraries are linked correctly. Compiling lpac myself would cause unnecessary difficulties for me, that's why I'm asking, if somebody knows how to solve this problem. Some information:
```
root@OpenMPTCProuter:/lib# ldd /root/lpac_/lpac
        /lib64/ld-linux-x86-64.so.2 (0x7f576751e000)
        libpcsclite.so.1 => /usr/lib/libpcsclite.so.1 (0x7f57674f1000)
        libcurl.so.4 => /usr/lib/libcurl.so.4 (0x7f5767495000)
        libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7f576751e000)
        libgcc_s.so.1 => /lib/libgcc_s.so.1 (0x7f5767481000)
        libnghttp2.so.14 => /usr/lib/libnghttp2.so.14 (0x7f576745a000)
        libidn2.so.0 => /usr/lib/libidn2.so.0 (0x7f5767439000)
        libssl.so.1.1 => /usr/lib/libssl.so.1.1 (0x7f57673a9000)
        libcrypto.so.1.1 => /usr/lib/libcrypto.so.1.1 (0x7f57670e4000)
        libz.so.1 => /usr/lib/libz.so.1 (0x7f57670d0000)
        libunistring.so.2 => /usr/lib/libunistring.so.2 (0x7f5766f52000)
root@OpenMPTCProuter:/lib# ./ld-musl-x86_64.so.1 /root/lpac_/lpac chip info
No APDU driver found
root@OpenMPTCProuter:/lib# env
AT_DEVICE=/dev/ttyUSB4
USER=root
SHLVL=1
HOME=/root
OLDPWD=/root
LPAC_HTTP=curl
PS1=\u@\h:\w\$ 
ENV=/etc/shinit
LOGNAME=root
TERM=linux
PATH=/usr/sbin:/usr/bin:/sbin:/bin
LPAC_APDU=at
SHELL=/bin/ash
PWD=/lib
```
Would the easiest solution be to use another Linux distribution to set up the esim with lpac? (more extensive distros with preinstalled libraries)

**Comment by CoelacanthusHex** [comment]
> root@OpenMPTCProuter:/lib# ./ld-musl-x86_64.so.1 /root/lpac_/lpac chip info

Why use the dynamic loader of musl? lpac-linux-x86_64.zip is compiled with glibc, you should use glibc's dynamic loader (as ldd said, it is named ld-linux-x86-64.so.2).

**Comment by CoelacanthusHex** [comment]
> This issue sseems to arise on the latest version of lpac, I downloaded the previous release 2.0.2 and it wouldn't display the error. 2.1.0 gives the error both on Windows 10 and Linux x64. Unfortunately I am not familiar with C development and especially the cMake, but looking at the source code I believe the only way for this error to be thrown is if lpac has been compiled without AT APDU driver option.

AT APDU driver will only be compiled when platform is Linux by default.

**Comment by rdtmaster** [comment]
> > This issue sseems to arise on the latest version of lpac, I downloaded the previous release 2.0.2 and it wouldn't display the error. 2.1.0 gives the error both on Windows 10 and Linux x64. Unfortunately I am not familiar with C development and especially the cMake, but looking at the source code I believe the only way for this error to be thrown is if lpac has been compiled without AT APDU driver option.
> 
> AT APDU driver will only be compiled when platform is Linux by default.

I have downloaded the Linux binary from releases page and set following env variables :
```
LPAC_APDU=at
LPAC_DEVICE=/dev/ttyS0
```
Latest version gives the error whilst v2.0.2 can connect to the device.
Has any of the env variable names or format changed since v2.0.2?
