### ISSUE TITLE
Does not support SIM7600

### ISSUE THREAD

**Issue by SkyEng1neering** [estkme-group/lpac#168]
Hi, could you share devices list which lpac was tested with? 

We tried to use it with SIM7600 + st4sim-200 and it works with bootstrap profile in the eSIM, but profiles management does not work with this setup, neither AT commands (as SIM7600 does not support any eSIM AT commands) nor via qmi (i guessed any modem should work with eSIM via qmi + APDU commands but it doesn't). We gonna change the modem but we need to know which ones are workable with lpac, could you help with it?

**Comment by rdtmaster** [comment]
Hello @SkyEng1neering
I had high interest in this st4sim-200 MCU however I found out it is a M2M eSIM which has different specification. I don't know anyone who has it so could you please try the following commands
```
at+csim=30,"80AA00000AA9088100820101830107"
at+csim=42,"01A4040010A0000005591010FFFFFFFF8900000300"
at+csim=22,"81E2910006BF3E035C015A"
```
And report the result?
If you want I have an experimental driver that works via csim command that is supported by most modems.

**Comment by SkyEng1neering** [comment]
> Hello @SkyEng1neering I had high interest in this st4sim-200 MCU however I found out it is a M2M eSIM which has different specification (mostly unknown to me since I am aware only of consumer eSIM specs). I don't know anyone who has it so could you please try the following commands
> 
> ```
> at+csim=30,"80AA00000AA9088100820101830107"
> at+csim=42,"01A4040010A0000005591010FFFFFFFF8900000100"
> at+csim=22,"81E2910006BF3E035C015A"
> ```
> 
> And report the result? (if the last command returned "6115", issue `at+csim=10,"81C0000015"`). If you want I have an experimental driver that works via csim command that is supported by most modems. If I were you I'd investigate whether the ST chip is a real issue here, before changing the modem. Also do you have an USB card reader (if the ST4SIM chip is in a nano form factor and is not soldered you can use it with any CCID compliant reader)? And does this simcom module support QMI mode?
> 
> I am really interested in this chip so if you want to share information could you kindly leave any contact detail because an an-depth discussion might be outside of scope of this repo/issues section
> 
> Last but not least, I recall reading a reply of STMicroelectronics staff saying that their M2M module is data only and won't send/receive SMS/voice. Don't know how true is this.

Hi @rdtmaster! Thank you for your reply. Sure, we will try the commands and share the results soon. By the way i expected that st4sim-200 should support consumer eSIM operations as it could store few profiles in the internal memory... Could you recommend some eSIM chips that support consumer specs? At the moment we have only st4sim-200 but we'll try other options too, thank you for the recommendations.

Regarding other questions - SIM7600 supports qmi, and we don't have the USB card reader (we use st4sim in the solderable chip form factor). We did not test if the st4sim-200 supports voice/SMS as we gonna use it for data transfer only. 

My contacts are: 
@dockdock - Telegram, 
https://www.linkedin.com/in/aleks63/, 
awarder64@gmail.com

But i guess it would be great to discuss main things here as it will be useful for other guys that as new in implementing eSIM as me in the future.

**Comment by SkyEng1neering** [comment]
AT commands results:
```
at+csim=30,"80AA00000AA9088100820101830107"
+CSIM: 4,"9000"

OK
at+csim=42,"01A4040010A0000005591010FFFFFFFF8900000100"
+CSIM: 4,"611A"

OK
at+csim=22,"81E2910006BF3E035C015A"
+CSIM: 4,"6985"

OK

```

**Comment by SkyEng1neering** [comment]
@rdtmaster i got you. Thank you so much for your comments, we'll try to obtain some consumer eSIMs and make experiments. I'll come back here to share the results with the sim7600 when i'll have some new info.
