### ISSUE TITLE
Multi-License

### ISSUE THREAD

**Issue by estkme** [estkme-group/lpac#20]
Currently lpac using AGPLv3 as single license.

in future I want change it to multiple license by sub-projects to make licenses not such aggressive.

As draft 
1. The launcher (cli wrapper , under src directory ) will remain in AGPLv3, with a commercial license.
2. The interfaces will change to MIT license 
3. The API framework (libeuicc, code under  euicc directory) will change to LGPLv2 with a commercial license.

Any suggestions?

**Comment by septs** [comment]
https://en.wikipedia.org/wiki/GPL_linking_exception
