### ISSUE TITLE
Is possible to get LPAC working on some cheap 4G dongle (UFIxxxx, openstick related) ?

### ISSUE THREAD

**Issue by dev-techmoe** [estkme-group/lpac#35]
They have a built-in e-sim chip, and a SIM slot, can we control it using LPAC?

I tried build and run LPAC on it (running a Debian system customized by [OpenStick Team](https://github.com/OpenStick)) but still got

```
SCardListReaders() failed: 8010002E
APDU library init error
```

But pcscd is running.

```
# systemctl status pcscd
● pcscd.service - PC/SC Smart Card Daemon
     Loaded: loaded (/lib/systemd/system/pcscd.service; indirect; vendor preset: enabled)
     Active: active (running) since Sat 2024-02-03 16:54:33 CST; 6s ago
TriggeredBy: ● pcscd.socket
       Docs: man:pcscd(8)
   Main PID: 573 (pcscd)
      Tasks: 3 (limit: 403)
     Memory: 772.0K
        CPU: 18ms
     CGroup: /system.slice/pcscd.service
             └─573 /usr/sbin/pcscd --foreground --auto-exit
```

Any idea for debugging this? Or it's an impossible things perhaps? 

Thank you.

**Comment by damonto** [comment]
That’s impossible; this project only supports customer eSIM, which implements SGP 2.2 features. Most of the 4G dongles are IOT eSIM, which implements SGP 1.1 only

**Comment by dev-techmoe** [comment]
> That’s impossible; this project only supports customer eSIM, which implements SGP 2.2 features. Most of the 4G dongles are IOT eSIM, which implements SGP 1.1 only

@damonto Thank you for your reply, and I also want to know it's possible to connect the external SIM card or not.

I have a DIY removable euicc SIM card, and it can be control using [sparkcyf/LPAdesktop](https://github.com/sparkcyf/LPAdesktop) on my Windows PC, it's possible to control it by using LPAC on this 4G dongle? Thank you.

**Comment by damonto** [comment]
It’s possible, You need a CCID(PCSC) reader. You may also need to install the CCID driver on your device.

**Comment by dev-techmoe** [comment]
> It’s possible, You need a CCID(PCSC) reader. You may also need to install the CCID driver on your device.

I mean that is it possible to do that without any other devices? Just LPAC + euicc SIM card on dongle, like Android phone + OpenEUICC.

**Comment by damonto** [comment]
It's impossible because most 4G WiFi dongles are based on Qualcomm 410 or 210, which are very old CPUs. Consequently, they don't support AT+CCHO, AT+CCHC, AT+CGLA AT commands, making it impossible to communicate with eUICC. However, if you have documentation about the QCOM protocol (used by Qualcomm old CPUs), you may implement this function by yourself.

**Comment by dev-techmoe** [comment]
> It's impossible because most 4G WiFi dongles are based on Qualcomm 410 or 210, which are very old CPUs. Consequently, they don't support AT+CCHO, AT+CCHC, AT+CGLA AT commands, making it impossible to communicate with eUICC. However, if you have documentation about the QCOM protocol (used by Qualcomm old CPUs), you may implement this function by yourself.

@damonto I get it, thank you for your answers. ❤️

**Comment by pielgrzym** [comment]
Is there any LTE modem that is using usb that would  work with eUICC? Perhaps some 5G modem? It's super hard to find compatible devices based on AT commands alone, hence the question.

**Comment by pielgrzym** [comment]
Thanks @bam80 !
