### ISSUE TITLE
Usage issues - Safe Card reader requirement

### ISSUE THREAD

**Issue by adamwlodarczyk1024** [estkme-group/lpac#36]
I'm encountering an issue while trying to execute the command mentioned in the readme to create profile

`./lpac profile download -s rsp.truphone.com -m "QR-G-5C-1LS-1W1Z9P7"
`

However, I'm receiving an error related to the APDU:

```
SCardListReaders() failed: 8010002E
APDU library init error

```
I've verified that the pcscd service is active:

```
● pcscd.service - PC/SC Smart Card Daemon
     Loaded: loaded (/lib/systemd/system/pcscd.service; indirect; vendor preset: enabled)
     Active: active (running) since Mon 2024-02-05 13:09:20 CET; 40s ago
TriggeredBy: ● pcscd.socket
       Docs: man:pcscd(8)
   Main PID: 3023594 (pcscd)
      Tasks: 3 (limit: 18841)
     Memory: 720.0K
        CPU: 10ms
     CGroup: /system.slice/pcscd.service
             └─3023594 /usr/sbin/pcscd --foreground --auto-exit

```

**Questions:**

Does the error indicate that connecting the reader is required when activating the SIM using the LPAC tool?
Will the SIM card added by LPAC be visible in ModemManager?
In the tool cli commands is info about APDUand HTTP driver, what it excatly mean? Can we use just http to create SIM?

**Comment by damonto** [comment]
Do you have a PC/SC smart card reader or a modem that supports AT+CCHO/CGLA/CCHC commands? If not, you may not be able to download a profile. Additionally, you must have an eUICC card or chip that implements SGP.22 features.

**Comment by adamwlodarczyk1024** [comment]
Thanks for the quick reply. I could not find these commands(CCHO/CGLA/CCHC) in the AT guides for my modems, which are Telit MV32 and Sierra Wireless EM9191. I tried to execute your commands on my modems, which as expected end with error messages.

**Comment by damonto** [comment]
If your modem does not support those commands you will not be able to use LPAC.

**Comment by adamwlodarczyk1024** [comment]
thanks for help! I will try to find another device which support these commands to test your amazing tool
