### ISSUE TITLE
modem compatibility list

### ISSUE THREAD

**Issue by bam80** [estkme-group/lpac#64]
Hi, I'm newbie,
could you clarify what esim-compatible modems are supported?

I'm interesting if I could use the project in OpenWrt router.

**Comment by damonto** [comment]
If your modem supports these AT+CCHO/AT+CGLA/AT+CCHC at commands, you may be able to use lpac on your OpenWrt router.

**Comment by bam80** [comment]
Do you know some modems supporting this?
Quectel, etc?

**Comment by damonto** [comment]
I can't provide a list of modems that support those commands. You could reach out to the manufacturer's support team for more information. 

AFAIK, most newer versions of Quectel modems support these commands.

**Comment by bam80** [comment]
> If your modem supports these AT+CCHO/AT+CGLA/AT+CCHC AT commands, you may be able to use lpac on your OpenWrt router.

Thanks.
Are these commands enough for the all operations, e.g. profile downloading, etc.?

**Comment by damonto** [comment]
I'm not entirely certain, but lpac only requires these commands. Some older modems may not recognize eUICC

**Comment by bam80** [comment]
> If your modem supports these AT+CCHO/AT+CGLA/AT+CCHC AT commands, you may be able to use lpac on your OpenWrt router.

My modem is Quectel EP06, could somebody help me to determine if these AT commands are supported?
If not, are there any other options to use eSIM adapter with `lpac` on this modem?
Maybe [QMI backend](https://github.com/estkme-group/lpac/pull/70)/[MBIM wrapper](https://github.com/stich86/lpac-libmbim-wrapper/)?

I would be appreciate for any help.
@z3ntu @stich86

Thanks.

**Comment by bam80** [comment]
> If your modem supports these AT+CCHO/AT+CGLA/AT+CCHC AT commands, you may be able to use lpac on your OpenWrt router.

FWIW, I don't see these AT commands in the modem manual:
https://onlinenik.ru/storage/download/Quectel_EP06-E_AT_Commands_Manual.pdf

Do I still have chances to use `lpac` with this modem?

**Comment by stich86** [comment]
> > If your modem supports these AT+CCHO/AT+CGLA/AT+CCHC AT commands, you may be able to use lpac on your OpenWrt router.
> 
> 
> 
> FWIW, I don't see these AT commands in the modem manual:
> 
> https://onlinenik.ru/storage/download/Quectel_EP06-E_AT_Commands_Manual.pdf
> 
> 
> 
> Do I still have chances to use `lpac` with this modem?

Does eSIM work on Windows?
If yes you can try my MBIM wrapper (I'll try to create native back-end like @z3ntu has done for QMI

**Comment by stich86** [comment]
Not all Quectel modem has AT commands to interact with eSIM (especially if it doesn't support). If you don't have the commands nothing to do (you can at least try to ask Quectel if they have firmware that support it).

At least if you using physical eSIM (like eSIM.me), it can be provisioned using MBIM or QMI (MBIM could works, not all module support logical channel over QMI)

**Comment by bam80** [comment]
> At least if you using physical eSIM (like eSIM.me), it can be provisioned using MBIM or QMI (MBIM could works, not all module support logical channel over QMI)

You mean, I should be able to do it with every modem supporting MBIM/QMI, regardless of the AT commands support?
