### ISSUE TITLE
ECIES of 5G: add support in UICCCapability

### ISSUE THREAD

**Issue by ValeZAA** [estkme-group/lpac#65]
berTlvFileSupport(19), -- BER TLV files  dfLinkSupport(20),      -- Linked Directory Files  
cat-tpSupport (21), -- CAT_TP support by any SD with SCP80 
 get-identitySupport(22), -- Support of GET IDENTITY as defined in ETSI TS 102 221 and the associated interface for SUCI derivation as defined in 3GPP TS 31.130  
profile-a-x25519Support(23), -- Support of ECIES Profile A as described in 3GPP TS 33.501 
 profile-b-p256Support(24) -- Support of ECIES Profile B as described in 3GPP TS 33.501 }

Last page in here https://trustedconnectivityalliance.org/wp-content/uploads/2020/01/Profile-interoperability-technical-specification-V2.3-5G-early-deployment-application-note.pdf

See https://github.com/estkme-group/lpac/blob/459bb15a9915b88b2aef9b1e873a94790673a39c/euicc/es10c_ex.c#L87
And 

https://github.com/estkme-group/lpac/blob/459bb15a9915b88b2aef9b1e873a94790673a39c/asn1/rsp.asn#L88

**Comment by estkme** [comment]
Thanks for your suggestions.

Our current goal is the implementation of the SGP.22 2.2.2 standard, and we will delay the implementation of the new standard for a long time.

If you really want to make this real, please submit a PR for it and make sure it won't break any SGP.22 2.2.2 compatible. We will happy to accept it.

**Comment by ValeZAA** [comment]
My 5ber card is 2.3.1 version. This is just parsing of capability. It does not affect anything.
