### ISSUE TITLE
how to specify AT command device

### ISSUE THREAD

**Issue by AndySchroder** [estkme-group/lpac#73]
When using the `at` APDU Backend, how do we specify what device to use? For example, we can have `/dev/wwan0at1` and `/dev/ttyUSB3` depending on the modem and how it is attached and the number of modems attached.

**Comment by damonto** [comment]
`AT_DEVICE=/dev/ttyUSB3 lpac chip info`

**Comment by AndySchroder** [comment]
if we skip that variable definition, will it auto search?

**Comment by damonto** [comment]
No, It will use the default value. `/dev/ttyUSB0`

**Comment by AndySchroder** [comment]
Okay, any idea why I might have two ports available? How to decide which one to use?

```
$ ll /dev/wwan0at*
crw------- 1 root root 242, 2 Apr 13 13:57 /dev/wwan0at0
crw------- 1 root root 242, 3 Apr 13 13:57 /dev/wwan0at1
$ 
```
Also, any idea why they are not using the `dialout` group? Note, this is a PCIe modem, not USB modem.


However, I have another USB modem with the following `ttyUSB0 (qcdm), ttyUSB2 (at), ttyUSB3 (at)` devices. These do use `dialout`, but I'm not sure why there are so many devices to choose from.

```
crw-rw---- 1 root dialout 188, 0 Apr  9 19:37 /dev/ttyUSB0
crw-rw---- 1 root dialout 188, 2 Apr  9 19:37 /dev/ttyUSB2
crw-rw---- 1 root dialout 188, 3 Apr  9 19:37 /dev/ttyUSB3
```

**Comment by damonto** [comment]
It depends on your modem, and both ttyUSB2 and ttyUSB2 can work normally in most cases.

**Comment by AndySchroder** [comment]
> It depends on your modem, and both ttyUSB2 and ttyUSB2 can work normally in most cases.

Do you mean `ttyUSB2` and `ttyUSB3`?

**Comment by AndySchroder** [comment]
Okay, trying to use `/dev/ttyUSB2`, but it doesn't seem to be working. Not sure if it is a different issue though:

```
$ 
$ picocom -cqb 9600 /dev/ttyUSB2
ATI

Quectel
EM120R-GL
Revision: EM120RGLAUR02A07M4G

OK
$ 
$ 
$ export AT_DEVICE=/dev/ttyUSB2
$ export LPAC_APDU=at
$ 
$ ./lpac chip info
{"type":"lpa","payload":{"code":-1,"message":"euicc_init","data":""}}
$ 
$ ll /dev/ttyUSB2
crw-rw---- 1 root dialout 188, 2 May  5 13:48 /dev/ttyUSB2
$ 
$ groups
dc dialout sudo gpio spi
$ 

```

**Comment by AndySchroder** [comment]
By the way, I tried running `sudo mmcli -m 0 --set-primary-sim-slot=2` so that the eSIM would be in use instead of the physical SIM, and that didn't seem to help (although it may be totally unrelated).

**Comment by AndySchroder** [comment]
Also, I get the same result if I try to use `/dev/ttyUSB3`.

**Comment by damonto** [comment]
You must make sure that your modem has a built-in eUICC chip, or that you have inserted a removable eUICC.
AFAIK, The eSIM function of Quectel EM120R-GL is optional, so your modem may not have it.

**Comment by estkme** [comment]
Since this is a "how to", future discuss is still available, but I prefer this issue closed.

**Comment by AndySchroder** [comment]
I can confirm my modem did not actually have a built in eUICC chip in it. Getting a removable eUICC worked.

However, I can't seem to use the at devices while modem manager is running, so modem manager needs to be stopped in order for lpac to be able to work.
