### ISSUE TITLE
issues with installation instructions

### ISSUE THREAD

**Issue by AndySchroder** [estkme-group/lpac#75]
Tried following your installation instructions starting here: https://github.com/estkme-group/lpac/blob/ee4b208186a9a53f918db7391616905d5a83a265/README.md?plain=1#L38 .

So far, I've noticed a few issues:
1. I needed to run `sudo apt update` first.
2. When running `./scripts/build.sh make` I get `./scripts/build.sh: line 53: zip: command not found`. The fix was to run `sudo apt install zip`.
3. No `output` directory exists after compiling. Instead there is a file `lpac-linux-aarch64.zip` that I then need to unzip somewhere else.

**Comment by damonto** [comment]
@septs Please update README.md and build.sh

**Comment by AndySchroder** [comment]
This issue is fixed in existing commits and https://github.com/estkme-group/lpac/pull/106 .
