### ISSUE TITLE
Support for esim.me card

### ISSUE THREAD

**Issue by iBobik** [estkme-group/lpac#77]
Hello,
I use [esim.me](https://esim.me) card HW in the LTE modem, but I have to manage it in the Android phone which is annoying. I would like to at least switch between already provisioned profiles without moving the card to the phone and back to the modem.

I asked support if I can at least switch profiles programmatically and they replied me:

> Use these 3 APDU commands (one command per line):
>
> 00 A4 04 00  10 A0 00 00 05  59 10 10 FF   FF FF FF 89  00 00 01 00
> 80 E2 91 00 1A BF 31 17 A0 12 4F 10 A0 00 00 05 59 10 10 FF FF FF FF 89 00 00 12 00 81 01 00
> 00 C0 00 00  06
> 
> The above example is using the eSIM profile with ID 12.
> 
> Each eSIM profile has its own ID, usually in a row, counting up.
> So you need to use the ID of the eSIM profile that is relevant to you.

Is this doable with lpac?

**Comment by septs** [comment]
it should be possible to manage eSIM.me (or 5ber.eSIM) using a PC/SC card reader

**Comment by septs** [comment]
You may need to port to the OpenWrt platform,
But the built-in AT APDU driver may not work.

If use PC/SC card reader, it can operate eSIM.me and 5ber.eSIM (EID prefix: `89086030`)

more see #73

**Comment by bam80** [comment]
> But the built-in AT APDU driver may not work.

Could you expand on this?
How to make sure if the built-in AT APDU driver works or not?

@iBobik could you test it?

**Comment by iBobik** [comment]
I will test it ASAP. Thanks.

**Comment by estkme** [comment]
Since this is a "how to use/whether it is supported" thread, conversion can still continue, but the issue will be closed.
