### ISSUE TITLE
5ber sim download profile error at es10b_authenticate_server

### ISSUE THREAD

**Issue by hamo** [estkme-group/lpac#92]
profile: `LPA:1$rsp.truphone.com$QRF-BETTERROAMING-PMRDGIR2EARDEIT5`
log:
```
C:\Program Files (x86)\EasyLPAC\lpac.exe profile download -s rsp.truphone.com -m QRF-BETTERROAMING-PMRDGIR2EARDEIT5
{"type":"progress","payload":{"code":0,"message":"es10b_get_euicc_challenge_and_info","data":null}}

{"type":"progress","payload":{"code":0,"message":"es9p_initiate_authentication","data":null}}

{"type":"progress","payload":{"code":0,"message":"es10b_authenticate_server","data":null}}

[DEBUG] [APDU] [TX] CLA: 81, INS: E2, P1: 91, P2: 00, Lc: 03, Data: BF 2E 00 
[DEBUG] [APDU] [RX] SW1: 61, SW2: 15, Data: 
[DEBUG] [APDU] [TX] CLA: 81, INS: C0, P1: 00, P2: 00, Lc: 15, Data: 
[DEBUG] [APDU] [RX] SW1: 90, SW2: 00, Data: BF 2E 12 80 10 77 1D BE D0 E7 3D E6 50 62 5B 7E 80 11 A7 76 BF 
[DEBUG] [APDU] [TX] CLA: 81, INS: E2, P1: 91, P2: 00, Lc: 03, Data: BF 20 00 
[DEBUG] [APDU] [RX] SW1: 61, SW2: 64, Data: 
[DEBUG] [APDU] [TX] CLA: 81, INS: C0, P1: 00, P2: 00, Lc: 64, Data: 
[DEBUG] [APDU] [RX] SW1: 90, SW2: 00, Data: BF 20 61 82 03 02 02 02 A9 2C 04 14 0B 13 59 63 3D 2A B4 69 76 1C A9 D8 2B 22 29 35 0D B7 22 D7 04 14 81 37 0F 51 25 D0 B1 D4 08 D4 C3 B2 32 E6 D2 5E 79 5B EB FB AA 2C 04 14 0B 13 59 63 3D 2A B4 69 76 1C A9 D8 2B 22 29 35 0D B7 22 D7 04 14 81 37 0F 51 25 D0 B1 D4 08 D4 C3 B2 32 E6 D2 5E 79 5B EB FB 
[DEBUG] [HTTP] [TX] url: https://rsp.truphone.com/gsma/rsp2/es9plus/initiateAuthentication, data: {"smdpAddress":"rsp.truphone.com","euiccChallenge":"dx2+0Oc95lBiW36AEad2vw==","euiccInfo1":"vyBhggMCAgKpLAQUCxNZYz0qtGl2HKnYKyIpNQ23ItcEFIE3D1El0LHUCNTDsjLm0l55W+v7qiwEFAsTWWM9KrRpdhyp2CsiKTUNtyLXBBSBNw9RJdCx1AjUw7Iy5tJeeVvr+w=="}
[DEBUG] [HTTP] [RX] rcode: 200, data: {"header":{"functionExecutionStatus":{"status":"Executed-Success"}},"transactionId":"000000001647FF73","serverSigned1":"MECACAAAAAAWR/9zgRB3Hb7Q5z3mUGJbfoARp3a/gxByc3AudHJ1cGhvbmUuY29thBCLyVeCntxpho8XjVv8TZyQ","serverSignature1":"XzdASqbFizzlojIt9xPluh3L+iBb2A/50OfzDrdmcHtAHdN/bFKmvYCDfyqHE77sJu9J88yIETrNRs4dGOP2PUYNFw==","euiccCiPKIdToBeUsed":"BBSBNw9RJdCx1AjUw7Iy5tJeeVvr+w==","serverCertificate":"MIICgzCCAiigAwIBAgIQZAVRhSGL0nffpH10bZlDJDAKBggqhkjOPQQDAjBEMRgwFgYDVQQKEw9HU00gQXNzb2NpYXRpb24xKDAmBgNVBAMTH0dTTSBBc3NvY2lhdGlvbiAtIFJTUDIgUm9vdCBDSTEwHhcNMjQwMjI3MDAwMDAwWhcNMjcwMjI2MjM1OTU5WjBsMQswCQYDVQQGEwJHQjEPMA0GA1UEBxMGTG9uZG9uMSUwIwYDVQQKExxUUCBHbG9iYWwgT3BlcmF0aW9ucyBMaW1pdGVkMQwwCgYDVQQLEwNSU1AxFzAVBgNVBAMTDjFHTE9CQUwgU00tRFArMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEb79IWSFYSQw31lOA9s8cFewC+w4Ey5eIo3FzG9KvpifqkGwSvQK3SgXAgWPOHv/cNXMy3NnDE5cpkiIh1qelHKOB0zCB0DAXBgNVHSABAf8EDTALMAkGB2eBEgECAQQwTQYDVR0fBEYwRDBCoECgPoY8aHR0cDovL2dzbWEtY3JsLnN5bWF1dGguY29tL29mZmxpbmVjYS9nc21hLXJzcDItcm9vdC1jaTEuY3JsMA4GA1UdDwEB/wQEAwIHgDAWBgNVHREEDzANiAsrBgEEAYHsRQEBATAdBgNVHQ4EFgQUGPBMVNemFzU7BmLhvQVUdNGc0z8wHwYDVR0jBBgwFoAUgTcPUSXQsdQI1MOyMubSXnlb6/swCgYIKoZIzj0EAwIDSQAwRgIhAL+/2SeUldiglTHlXJcoyZt7dTNin7PVZKwMXK0JQFlyAiEA9Lr0dY6U1AOm9m63RqPG0vvyThkGcSgYLneU+tH6H7o="}
[DEBUG] [APDU] [TX] CLA: 81, INS: E2, P1: 11, P2: 00, Lc: 78, Data: BF 38 82 03 52 30 40 80 08 00 00 00 00 16 47 FF 73 81 10 77 1D BE D0 E7 3D E6 50 62 5B 7E 80 11 A7 76 BF 83 10 72 73 70 2E 74 72 75 70 68 6F 6E 65 2E 63 6F 6D 84 10 8B C9 57 82 9E DC 69 86 8F 17 8D 5B FC 4D 9C 90 5F 37 40 4A A6 C5 8B 3C E5 A2 32 2D F7 13 E5 BA 1D CB FA 20 5B D8 0F F9 D0 E7 F3 0E B7 66 70 7B 40 1D D3 7F 6C 52 A6 BD 80 83 7F 2A 87 13 BE EC 26 
[DEBUG] [APDU] [RX] SW1: 90, SW2: 00, Data: 
[DEBUG] [APDU] [TX] CLA: 81, INS: E2, P1: 11, P2: 01, Lc: 78, Data: EF 49 F3 CC 88 11 3A CD 46 CE 1D 18 E3 F6 3D 46 0D 17 04 14 81 37 0F 51 25 D0 B1 D4 08 D4 C3 B2 32 E6 D2 5E 79 5B EB FB 30 82 02 83 30 82 02 28 A0 03 02 01 02 02 10 64 05 51 85 21 8B D2 77 DF A4 7D 74 6D 99 43 24 30 0A 06 08 2A 86 48 CE 3D 04 03 02 30 44 31 18 30 16 06 03 55 04 0A 13 0F 47 53 4D 20 41 73 73 6F 63 69 61 74 69 6F 6E 31 28 30 26 06 03 55 04 03 
[DEBUG] [APDU] [RX] SW1: 90, SW2: 00, Data: 
[DEBUG] [APDU] [TX] CLA: 81, INS: E2, P1: 11, P2: 02, Lc: 78, Data: 13 1F 47 53 4D 20 41 73 73 6F 63 69 61 74 69 6F 6E 20 2D 20 52 53 50 32 20 52 6F 6F 74 20 43 49 31 30 1E 17 0D 32 34 30 32 32 37 30 30 30 30 30 30 5A 17 0D 32 37 30 32 32 36 32 33 35 39 35 39 5A 30 6C 31 0B 30 09 06 03 55 04 06 13 02 47 42 31 0F 30 0D 06 03 55 04 07 13 06 4C 6F 6E 64 6F 6E 31 25 30 23 06 03 55 04 0A 13 1C 54 50 20 47 6C 6F 62 61 6C 20 4F 70 
[DEBUG] [APDU] [RX] SW1: 90, SW2: 00, Data: 
[DEBUG] [APDU] [TX] CLA: 81, INS: E2, P1: 11, P2: 03, Lc: 78, Data: 65 72 61 74 69 6F 6E 73 20 4C 69 6D 69 74 65 64 31 0C 30 0A 06 03 55 04 0B 13 03 52 53 50 31 17 30 15 06 03 55 04 03 13 0E 31 47 4C 4{"type":"lpa","payload":{"code":-1,"message":"es10b_authenticate_server","data":""}}


```

**Comment by estkme** [comment]
Thanks for report.

Since we don't have a 5ber card, this issue will be delayed to investigate.

**Comment by bam80** [comment]
I was about to buy a 5ber card.
Does this error means I would better wait?

**Comment by Lasibian** [comment]
I just tried downloading a profile from betterroaming to my 5ber card. It worked fine. Are you using lpac 2.0.1? I had issues with the older versions.

**Comment by hamo** [comment]
> I just tried downloading a profile from betterroaming to my 5ber card. It worked fine. Are you using lpac 2.0.1? I had issues with the older versions.

yes, it is v2.0.1. what's your firmware version of the 5ber sim card? mine is 
 "profileVersion": "2.3.1",
  "svn": "2.2.2",
  "euiccFirmwareVer": "4.2.0",
  "globalplatformVersion": "2.3.0",


I just did a firmware upgrade in the official 5ber app before using it with lpac. Hope this is not the root cause.

**Comment by Lasibian** [comment]
Seems to be the same. I got a firmware update notification in the 5ber app, but I did not install it.
  "profileVersion": "2.3.1",
  "svn": "2.2.2",
  "euiccFirmwareVer": "4.2.0",
  "globalplatformVersion": "2.3.0"

**Comment by hamo** [comment]
> Seems to be the same. I got a firmware update notification in the 5ber app, but I did not install it. "profileVersion": "2.3.1", "svn": "2.2.2", "euiccFirmwareVer": "4.2.0", "globalplatformVersion": "2.3.0"

that's wired. And after reporting this, I tried my card with 5ber official app, it works well.

**Comment by bam80** [comment]
Could you guys maybe try to download the same profile, to make it clear what's the reason?

In my understanding that would require to share the QR-code between both of you but that must be not a big security risk considering QR code usually invalidates after few downloads anyway?

**Comment by Lasibian** [comment]
Betterroaming seems to use the same QR code for everyone. So here it goes:

lpac.exe profile download -s rsp.truphone.com -m QRF-BETTERROAMING-PMRDGIR2EARDEIT5
{"type":"progress","payload":{"code":0,"message":"es10b_get_euicc_challenge_and_info","data":null}}

{"type":"progress","payload":{"code":0,"message":"es9p_initiate_authentication","data":null}}

{"type":"progress","payload":{"code":0,"message":"es10b_authenticate_server","data":null}}

{"type":"progress","payload":{"code":0,"message":"es9p_authenticate_client","data":null}}

{"type":"progress","payload":{"code":0,"message":"es10b_prepare_download","data":null}}

{"type":"progress","payload":{"code":0,"message":"es9p_get_bound_profile_package","data":null}}

{"type":"progress","payload":{"code":0,"message":"es10b_load_bound_profile_package","data":null}}

{"type":"lpa","payload":{"code":0,"message":"success","data":null}}

**Comment by itenosgh** [comment]
> I just did a firmware upgrade in the official 5ber app before using it with lpac. Hope this is not the root cause.

That's scary news. I imagined something similar and did not upgrade my firmware for that reason. Could you try with another eSIM in order to rule out that it's not only a betterroaming problem?
If you don't have any other profile available you can use this one here with my referral code. It gives you 500 MB free data worldwide and don't worry, it's not spam because I do not receive anything in return until you eventually continue using them and buy a plan. It's just for the sake of finding out if the firmware update messed up the possibility to use LPAC instead of their native app.
http://eskimo.travel/JURGEN172671

**Comment by AndySchroder** [comment]
I just received a new 5ber eSIM card yesterday and it seems to work fine.

**Comment by bam80** [comment]
The question is if it continues to work after it's firmware update

**Comment by AndySchroder** [comment]
'euiccFirmwareVer': '4.2.0'

**Comment by itenosgh** [comment]
> I just received a new 5ber eSIM card yesterday and it seems to work fine.

Seems that you didn't understand the issue here. The 5ber card out of the box works fine with EasyLPAC but user @hamo  did perform a firmware update within the official 5ber app and after it didn't work anymore with EasyLPAC. Unfortunately he didn't reply here anymore. 
So the question for you @AndySchroder is: did you upgrade your firmware through the official 5ber app prior of using EasyLPAC to write a new profile to the card?
Thank you for helping out

**Comment by AndySchroder** [comment]
I did not use a 5ber app at all, only lpac.

**Comment by bam80** [comment]
So the question persists.
@AndySchroder you are welcome to answer it through the experiment above but be aware there is a chance you lose `lpac` functionality.

**Comment by estkme** [comment]
Issues are not community discussion boards, and this current issue has the tendency to become the former.

estkme-group has its own brand of eUICC products, so serve other brands is **not** the goal of this project, and we currently do not have the energy to do such a thing.

The issue will be closed, but discussion is still welcome.

**Comment by robimarko** [comment]
@bam80 Well, my modem seems so quirky, it constantly fails on `es10b_authenticate_server`, tried 2 different profiles with completely different SM-DP servers

**Comment by ValeZAA** [comment]
![image](https://github.com/user-attachments/assets/aaccec1a-67d0-4973-b16e-894ea73e2ece)
Works fine here on my 5ber, but I updated the firmware / certificates in 5ber already. Did not check what happens before that.

Test profile from here BTW https://euicc-manual.osmocom.org/docs/rsp/known-test-profile/

**Comment by bam80** [comment]
> The issue will be closed, but discussion is still welcome.

@estkme the issue still persists, please reopen to make community aware of it and further investigation.

**Comment by ValeZAA** [comment]
> > The issue will be closed, but discussion is still welcome.
> 
> @estkme the issue still persists, please reopen to make community aware of it and further investigation.

Did you even buy 5ber? remember new 5ber after circa May 2024 are already coming with firmware installed. Remember those are just certificates updates, though there is also an applet update that can do something.

**Comment by bam80** [comment]
@ValeZAA yes, I do have 5ber esim and experiencing the same problem.
I didn't do any updates on the card.

I wonder if this problem has something to do with SSL library in use (OpenSSL, Mbed TLS, etc.)

**Comment by Lasibian** [comment]
I could imagine that it could be related to the card reader and the driver. What are you guys using?

I have this one: https://www.amazon.de/gp/product/B0CKQ8SSB4
I also needed a good driver, the default driver that comes with Windows did not work well. This is the one I'm using:
https://www.catalog.update.microsoft.com/Search.aspx?q=Alcor%20Micro%20USB%20Smart%20Card%20Reader
There's quite a lot of download links for the driver. But they all seem to point to the same download.

I still haven't updated the 5ber firmware.

I think a SSL issue is rather unlikely. That would hit everyone.

**Comment by ValeZAA** [comment]
>I still haven't updated the 5ber firmware.

It is not a real firmware, they just update the certificate. It will not work for a lot of providers, like CellFi on the old certificate. 

>I think a SSL issue is rather unlikely. That would hit everyone.

That certificate is not using TLS. Ancient SSL does not even exist anymore... It is not used like that, it exists to identify the root of trust and intemediate certificates. You can see the certs here https://euicc-manual.osmocom.org/docs/pki/ci/#gsma-live

>I didn't do any updates on the card.

Then what are we arguing here? The old certifiicate almost certainly does not work.

**Comment by ValeZAA** [comment]
> Seems to be the same. I got a firmware update notification in the 5ber app, but I did not install it. "profileVersion": "2.3.1", "svn": "2.2.2", "euiccFirmwareVer": "4.2.0", "globalplatformVersion": "2.3.0"

Those numbers do not change when you update the "firmware".

**Comment by bam80** [comment]
> Then what are we arguing here? The old certifiicate almost certainly does not work.

The 5ber card, despite not being updated, still works in 5ber app for local carrier Megafon.

> It is not a real firmware, they just update the certificate. It will not work for a lot of providers, like CellFi on the old certificate.

> You can see the certs here https://euicc-manual.osmocom.org/docs/pki/ci/#gsma-live

Those test profiles didn't work for me, if you think the card updating is relatively safe and could help for these profiles work, I could take the risk and do so.

**Comment by ValeZAA** [comment]
Yes, you should update.
