### ISSUE TITLE
EasyEUICC in HUAWEI cannot scan QR code

### ISSUE THREAD

**Issue by RickySJTU** [estkme-group/lpac#96]
When I use app to scan QR code, the page would switch to Log Page, and nothing changes. I search the error in web, find it often appears in HUAWEI. Do you know what problems and solutions, please?
![Screenshot_20240518_165440_im angry easyeuicc](https://github.com/estkme-group/lpac/assets/69800918/1a00f5e0-cf62-4e13-bf26-83f15a168112)
![Screenshot_20240518_182339_im angry easyeuicc](https://github.com/estkme-group/lpac/assets/69800918/b90802ad-7afa-4bd1-a71d-4274c7a8bef0)

**Comment by damonto** [comment]
This is lpac repository not EasyEUICC. If you have problem with EasyEUICC please submit an issue at https://gitea.angry.im/PeterCxy/OpenEUICC/
