### ISSUE TITLE
document all environmental variables

### ISSUE THREAD

**Issue by AndySchroder** [estkme-group/lpac#98]
We had https://github.com/estkme-group/lpac/issues/73 which uncovered a very useful environmental variable which was added to the documentation in https://github.com/estkme-group/lpac/commit/6e468944cf06f7ba0c70e11365265845a0efc3c0#diff-e728b7e5cd9058fef9defdfd11fed04ef21296a5e8540287d4a746b096ce1242. I'm sure there are many more? Now I see https://github.com/estkme-group/lpac/pull/97 which introduces another. https://github.com/estkme-group/lpac/pull/70 introduces a new back end, but I am not sure hot to actually activated it (I'm assuming there is a new environmental variable for it?). Can we get a full list of environmental variables in `ENVVARS.md` and make that as a standard before merging new commits that any new environmental variables must be documented?

**Comment by damonto** [comment]
updated.
