### ISSUE TITLE
add aarch64-linux binary release downloads

### ISSUE THREAD

**Issue by AndySchroder** [estkme-group/lpac#99]
For those that don't want to manually compile, please add a .zip and .deb file for aarch64-linux to https://github.com/estkme-group/lpac/releases so that we can run on 64bit arm processors.

**Comment by damonto** [comment]
We don’t have ARM runner now.

**Comment by AndySchroder** [comment]
you mean you don't have a device to test with?

**Comment by damonto** [comment]
If you need a Linux aarch64 binary file, you can compile it yourself. We will add it once GitHub provides a Linux ARM runner.

**Comment by AndySchroder** [comment]
It compiles fine on aarch64 for me, I can do it that way, it would just be more convenient to have it pre-built.

**Comment by AndySchroder** [comment]
However, if you can't do aarch64 right now, it would still be better if you named the file that you do have `lpac-2.0.1-x86_64.deb` instead of  `lpac-2.0.1-Linux.deb` so that it's more clear that it only works on x86_64 and not aarch64. Also, no need to put "Linux" in the file name because .deb files only work on Linux anyway, it's redundant. Also, for the standalone version,  `lpac-linux-x86_64.zip` I'd recommend making this `lpac-x86_64.tar.gz`. That is common convention, you don't need to add the word "Linux" in there.

**Comment by AndySchroder** [comment]
Does https://github.com/uraimo/run-on-arch-action work for you to get an ARM runner?

**Comment by AndySchroder** [comment]
> it would still be better if you named the file that you do have `lpac-2.0.1-x86_64.deb` instead of `lpac-2.0.1-Linux.deb` so that it's more clear that it only works on x86_64 and not aarch64. Also, no need to put "Linux" in the file name because .deb files only work on Linux anyway, it's redundant.

This comment is fixed in https://github.com/estkme-group/lpac/pull/106.

**Comment by unixfox** [comment]
hello @AndySchroder could you tell me how you compiled it in ARM? using cross compilation? or on an actual ARM device?

**Comment by AndySchroder** [comment]
On a raspi4.
